### PR TITLE
fix: downgrading torchmetrics due to import error

### LINKED ISSUE #73: [Bug] ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'
### :skull: Bug

I have built the docker-container today and executed the preprocessing command, which resulted in the following error message:

>root@fef61e129e56:/opt/code/nndet# nndet_prep 000
Traceback (most recent call last):
  File "/opt/conda/bin/nndet_prep", line 33, in <module>
    sys.exit(load_entry_point('nndet', 'console_scripts', 'nndet_prep')())
  File "/opt/conda/bin/nndet_prep", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/conda/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/code/nndet/scripts/preprocess.py", line 36, in <module>
    from nndet.planning import DatasetAnalyzer
  File "/opt/code/nndet/nndet/planning/__init__.py", line 2, in <module>
    from nndet.planning.experiment import PLANNER_REGISTRY
  File "/opt/code/nndet/nndet/planning/experiment/__init__.py", line 6, in <module>
    from nndet.planning.experiment.v001 import D3V001
  File "/opt/code/nndet/nndet/planning/experiment/v001.py", line 6, in <module>
    from nndet.ptmodule import MODULE_REGISTRY
  File "/opt/code/nndet/nndet/ptmodule/__init__.py", line 3, in <module>
    from nndet.ptmodule.base_module import LightningBaseModule
  File "/opt/code/nndet/nndet/ptmodule/base_module.py", line 24, in <module>
    import pytorch_lightning as pl
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/opt/conda/lib/python3.8/site-packages/torchmetrics/utilities/data.py)

This is possibly related to https://github.com/NVIDIA/DeepLearningExamples/issues/1113.

### Environment

```bash
$ nndet_env
----- PyTorch Information -----
PyTorch Version: 1.8.0a0+1606899
PyTorch Debug: False
PyTorch CUDA: 11.1
PyTorch Backend cudnn: 8005
PyTorch CUDA Arch List: ['sm_52', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_86']
PyTorch Current Device Capability: (7, 5)
PyTorch CUDA available: True


----- System Information -----
System NVCC: nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

System Arch List: 5.2 6.0 6.1 7.0 7.5 8.0 8.6+PTX
System OMP_NUM_THREADS: 1
System CUDA_HOME is None: True
System CPU Count: 12
Python Version: 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]


----- nnDetection Information -----
det_num_threads 9
det_data is set True
det_models is set True
```

How was nnDetection installed [`docker` | `source`]:
Docker

### PR DESCRIPTION
**Pull request by kapsner**
fixes #73

### CODE REVIEW

**Comment by mibaumgartner** [comment]
Hi @kapsner, thanks for the Issue and PR! Could you remove the docker file changes and add torchmetrics to the requirements.txt and pin its version there? (The error is not limited to the docker build but also fails for source installation and this change would fix both of them) 
I also setup a ci runner to hopefully catch some of the version errors earlier from now on :)

**Comment by mibaumgartner** [comment]
Thanks!

**Comment by kapsner** [comment]
Hi @mibaumgartner , sorry, the first PR was a quick and dirty solution - I have updated the Dockerfile and the requirements.txt accordingly.

However, I was not sure, which would be the minimum required version of torchmetrics working with nnDetection.

**Comment by mibaumgartner** [comment]
I think the inserted version should work fine for now, hopefully pytorch-lightning will fix the version issue from their side and we can remove the pinned version in the future (nnDet doesn't actually rely on torchmetrics).

**Pull request merged**
